# This is a basic workflow to help you get started with Actions

name: Build RPM package

# Controls when the workflow will run
on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: quay.io/centos/centos:stream9
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Installation dependencies
        run: dnf install -y dnf-plugins-core && dnf config-manager --set-enable crb && dnf install -y golang glibc-static rpmdevtools rpmlint git

